services:
    odoo-2:
        container_name: odoo-2
        image: odoo:17.0
        env_file: .env
        volumes:
            - ./etc/odoo:/etc/odoo
            - ./addons:/mnt/extra-addons
            - ./var/lib/odoo:/var/lib/odoo
        ports:
            - 8069:8069
        depends_on:
            - odoo-postgres-2
        networks:
            - odoo-network
    odoo-postgres-2:
        container_name: odoo-postgres-2
        image: postgres:16.1
        env_file: .env
        volumes:
            - ./var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
        networks:
            - odoo-network
networks:
    odoo-network:
        driver: bridge